# Generated by Django 3.2.8 on 2021-10-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Number', models.IntegerField()),
                ('BC', models.ImageField(upload_to='')),
                ('parent_ID', models.ImageField(upload_to='')),
                ('payslip', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PASSPORT_Number', models.IntegerField()),
                ('BC', models.ImageField(upload_to='')),
                ('parent_ID', models.ImageField(upload_to='')),
                ('payslip', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ADMIN_PANEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.applicationid')),
                ('passport_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.applicationpassport')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.userz')),
            ],
        ),
    ]
