# Generated by Django 3.2.8 on 2021-11-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userz',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='userz',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='userz',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userz',
            name='twitter',
        ),
    ]
