# Generated by Django 3.2.8 on 2021-11-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('users', models.CharField(max_length=200)),
                ('application_forms', models.ImageField(upload_to='')),
                ('payments', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.ImageField(upload_to='')),
                ('birth_certificate', models.ImageField(upload_to='')),
                ('lostOrStolen', models.CharField(max_length=200)),
                ('proofOfResidency', models.CharField(max_length=200)),
                ('identityType', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentOf', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LostOrStolen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentOf', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_Status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('ID_number', models.IntegerField(max_length=13)),
                ('password', models.CharField(max_length=200)),
                ('cPassword', models.CharField(max_length=200)),
            ],
        ),
    ]
